//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmaAnket.Dal.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerLine
    {
        public int ID { get; set; }
        public int AnswerID { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string Image { get; set; }
    }
}
